services:
  jupyterlab:
    restart: always
    build: .
    container_name: algodata
    volumes:
      - ./root_jupyter:/root/.jupyter
      - .:/work
    ports:
      - "8888:8888"
    command:
      jupyter-lab --allow-root --ip=0.0.0.0 --no-browser --NotebookApp.token='' --notebook-dir=/work